"""Prompt text for the clinic voice agent.

Phase 0: placeholders only. Phase 1: added PHASE1_SYSTEM_PROMPT (greeting + single scripted
turn). Phase 2: added PHASE2_SYSTEM_PROMPT (full slot-fill -> offer -> hold -> confirm ->
book -> close, driven by the scheduling-API tool calls in scheduling_tools.py).

The AI-disclosure line is mandatory (governance) and must appear in the greeting whenever the
agent runs. The full state-machine hardening (validation, per-state fallbacks) is Phase 3
following docs/build_spec.md; Phase 2 lets the LLM drive the flow from the prompt below.
"""

from __future__ import annotations

from datetime import date, timedelta, timezone
from datetime import datetime as _datetime
from zoneinfo import ZoneInfo

from . import tenant as _tenant
from .intents import SCHEDULING_INTENTS, Intent

# timezone: US/Eastern (America/New_York) — agent operates in clinic local time. The current
# time, "today", and the date→weekday reference table injected into the prompt are all resolved
# in this zone so the model reasons about the clinic's wall clock (e.g. "12:17 AM EDT, Tuesday
# July 7"), not UTC — otherwise near midnight local it can land on the wrong calendar day and
# misjudge which slots are still in the future. Mirrors CLINIC_TZ in scheduling_api/app/db.py.
CLINIC_TZ = ZoneInfo("America/New_York")

# Mandatory AI disclosure. Delivered in the GREETING_DISCLOSURE state.
AI_DISCLOSURE = (
    "You're speaking with an automated AI assistant."
)

# Call-recording consent. Spoken in the greeting on the telephony path (Phase 5), BEFORE
# any booking begins. Not spoken on the local dev path (nothing is recorded there).
# TODO: confirm exact consent wording for the target jurisdiction before a real deployment.
RECORDING_CONSENT = (
    "This call may be recorded for quality and scheduling purposes."
)

# Greeting delivered at the start of the call (GREETING_DISCLOSURE) on the LOCAL path.
_GREETING_TEMPLATE = (
    "Thanks for calling {clinic_name}. "
    f"{AI_DISCLOSURE} "
    "I can help you book an appointment. How can I help today?"
)
GREETING = _GREETING_TEMPLATE.format(clinic_name=_tenant.DEFAULT.name)

# Greeting for the TELEPHONY path: identical AI disclosure, plus the call-recording consent
# line, spoken up front before any booking. The disclosure and consent lead so both governance
# statements are delivered before the caller shares anything.
_TELEPHONY_GREETING_TEMPLATE = (
    "Thanks for calling {clinic_name}. "
    f"{AI_DISCLOSURE} "
    f"{RECORDING_CONSENT} "
    "I can help you book an appointment. How can I help today?"
)
TELEPHONY_GREETING = _TELEPHONY_GREETING_TEMPLATE.format(clinic_name=_tenant.DEFAULT.name)


# Scripted line spoken when the LLM request itself fails (Phase 10). The in-house event loop
# turns an LLM error into a spoken recovery instead of dead air, and the wording is fixed
# rather than model-generated for the obvious reason: the model is what just failed.
SYSTEM_ERROR_LINE = (
    "Sorry, I'm having trouble on my end. Could you say that again?"
)

# Phase 15. Spoken when a tool call has been in flight past its budget. Deterministic for the
# same reason as the line above: the model cannot narrate a wait it does not know it is in, and
# the alternative measured on live calls was silence the caller reads as a dropped line.
TOOL_FILLER_LINE = "Let me pull that up for you — one moment."

# Phase 15 — the warm handoff. Spoken BEFORE the SIP transfer so the caller knows what the
# silence and the ringing mean, and never generated by a model: the transfer usually fires
# because something is already going wrong.
HANDOFF_LINE = (
    "Let me get you to someone on our team who can help. "
    "Please hold for just a moment while I connect you."
)

# When no transfer destination is configured, the transfer fails, or there is nobody to
# transfer to (the local path). The promise made here is one the clinic's staff can keep from
# the escalation record, which is why it is a callback rather than "please call back".
HANDOFF_UNAVAILABLE_LINE = (
    "I'm sorry — I can't connect you to someone right now. "
    "I've flagged this for our staff and they'll call you back at this number as soon as they can."
)

# --- Emergency response (Phase 12) -------------------------------------------------------
# The single highest-stakes string in this repo, and the reason it is a constant rather than a
# prompt: a caller who says they cannot breathe must hear THESE words, identically, on every
# call, on every model, during a provider outage, and while the API is timing out. Nothing
# about this sentence is a judgement call the model should be making.
#
# It leads with the instruction rather than an apology or a preamble, because the caller may
# stop listening — or stop being able to listen — at any moment. It does not ask a follow-up
# question, does not attempt triage, and does not offer to book anything.
EMERGENCY_RESPONSE = (
    "This sounds like a medical emergency. Please hang up and call 9-1-1 right now, "
    "or go to your nearest emergency room. "
    "I'm an automated assistant and I can't help with emergencies."
)

# Only used if a model is ever put on this path, which it currently is not. Kept so the
# instruction exists in one place if Phase 15's warm transfer ever needs a model-mediated
# variant — and worded to forbid exactly the improvisation that would make it dangerous.
EMERGENCY_INSTRUCTION = (
    "The caller is describing a medical emergency. Do NOT triage, reassure, assess severity, "
    "ask follow-up medical questions, or offer an appointment. Tell them to hang up and call "
    "9-1-1 or go to the nearest emergency room, and say you cannot help with emergencies."
)


def greeting_for(mode: str, clinic_name: str | None = None) -> str:
    """Return the greeting for the given runtime mode and tenant.

    Telephony adds the call-recording consent line to the shared AI disclosure; local dev
    records nothing, so it uses the disclosure-only greeting.

    Only the clinic's NAME varies per tenant. The disclosure and the recording consent are
    fixed text in both greetings and are not a per-tenant setting — a clinic does not get to
    configure whether its callers are told they are talking to an AI.
    """
    template = _TELEPHONY_GREETING_TEMPLATE if mode == "telephony" else _GREETING_TEMPLATE
    return template.format(clinic_name=clinic_name or _tenant.current().name)

# Minimal Phase-1 system prompt. Scoped to greeting + disclosure + answering a single
# scripted turn (confirming the agent can help schedule). It deliberately does NOT do
# slot-filling, name/reason collection, or booking — that arrives with the scheduling-API
# tool calls (Phase 2) and dialogue hardening (Phase 4) in build_phase2_system_prompt() below,
# which is the prompt the running pipeline actually uses (see docs/build_spec.md).
PHASE1_SYSTEM_PROMPT = """\
You are the virtual scheduling assistant for Grove Family Clinic, speaking with a caller by
phone. You have already greeted the caller and disclosed that you are an automated AI
assistant.

Keep every reply to one or two short, natural sentences suitable for text-to-speech.

Scope for this build: you can confirm that you are able to help the caller book an
appointment and answer simple questions about that. Do NOT ask for available times, offer
specific appointment slots, collect the caller's name or reason for the visit, or book
anything yet — those capabilities are not enabled in this build. If the caller asks to
actually book, warmly confirm that you can help schedule an appointment and that the next
step will take their details.

Never invent clinic-specific facts (addresses, providers, hours). All data is synthetic;
never request detailed medical information.
"""

# --- Phase 2 system prompt --------------------------------------------------------------
# Full booking flow, driven by the LLM via the three scheduling-API tools (see
# scheduling_tools.py). The LLM decides when to call each tool; this prompt encodes the
# dialogue flow, tool-usage rules, the two hard branch cases (no availability, caller changes
# their mind), and PHI minimization. `{today}` is injected at build time so relative dates
# like "tomorrow" / "next Tuesday" resolve correctly — build via build_phase2_system_prompt().
# --- Phase 12: composable, intent-scoped prompt ------------------------------------------
# Through Phase 11 this was one 9,485-character template sent on every single turn, whatever
# the caller wanted. Most of it is the booking flow — the tool-usage rules, the offer/hold/
# confirm gate, the branch cases — which is dead weight when someone is asking for the address.
#
# It is now assembled per turn from a shared CORE plus the fragment the classified intent
# actually needs (see build_system_prompt). Measured effect, with the exact numbers in
# docs/build_spec.md: scheduling turns stay ~9 KB because those rules are load-bearing (every
# one of them fixes a defect the Phase-4 eval caught, and deleting them to hit a size target
# would trade a real regression for a nice number), while non-scheduling turns drop to ~2 KB.
#
# Caching interaction, worth knowing before "optimizing" this further: Phase 8 measured the
# cacheable prefix at 3,811 tokens against Haiku 4.5's 4,096 minimum. Shrinking prompts pushes
# them FURTHER below that floor. The right resolution is a model whose floor the prompt clears
# (Sonnet 4.6/5 and Opus 4.8 are 1,024), not a smaller prompt.

_CORE_TEMPLATE = """\
You are the virtual scheduling assistant for {clinic_name}, speaking with a caller by
phone. You have already greeted the caller and disclosed that you are an automated AI
assistant.

Today's date is {today} ({weekday}), and the current time is {now_local} — this is the clinic's
local time ({tz_label}). Reason about time in the clinic's local timezone. Speak appointment
times naturally (e.g. "Monday, July 6th at 9 AM"), never as raw timestamps.

STYLE: keep every reply to one or two short, natural sentences suitable for text-to-speech.
Ask for one thing at a time. Sound like a warm, competent front-desk coordinator who has done
this a thousand times — brief, unhurried, and human. Vary how you acknowledge answers instead
of reaching for the same word ("perfect", "great") every turn; use the caller's first name
occasionally rather than in every reply; and when someone shares something uncomfortable,
acknowledge it in a few words before moving on. If a caller's turn does arrive as a fragment,
answering it warmly ("take your time — I'm listening") is exactly right; keep that short. Never read out slot_id, hold_id, or reason_category codes — those
are internal. Whenever you still need something from the caller (their name, a reason, a
preferred day, a slot choice, or a yes/no), END your turn with a direct question for exactly
that — don't leave your turn on a statement when it is the caller's turn to answer.

PII MINIMIZATION: never read a caller's full name together with another identifier (a date of
birth, a phone number) in the same sentence — one identifier per sentence, always.
  WRONG: "I have your name as Dana Reyes and your date of birth as March 15th, 1990."
  WRONG: "I have you as Dana Reyes, and your date of birth is March 15th, 1990."
  RIGHT: "I have you as Dana Reyes. And the date of birth is March 15th, 1990 — correct?"
Mechanically: say the name, END THE SENTENCE with a full stop, then start a new sentence for the
date of birth. A comma, an "and", or a dash between them is the same mistake as no break at all.
This holds on the final read-back too. Do not repeat back a phone number or any government ID at all unless the
caller explicitly asks. Keep the reason to a short phrase and the symptom note to ONE compact sentence: collect
what the clinician needs to start this visit, and nothing beyond the concern the caller raised.

Never invent clinic facts (addresses, providers, hours, prices). All data is synthetic.

NEVER ANNOUNCE AN ACTION WITHOUT TAKING IT IN THE SAME REPLY. Words like "I'm holding that",
"let me check", "I'm booking you now" describe a TOOL CALL, and the tool call must be in this
same reply. There is no later — your turn ends when you stop, and the caller hears silence.
  WRONG: "I'm holding that for you." (no tool call in the reply)
  RIGHT: [call hold_slot] + "I'm holding that for you."
If you are not going to call the tool this turn, do not claim the action: ask the question you
actually need answered instead.

NEVER CLAIM AN ACTION YOU DID NOT TAKE. An appointment exists only when a tool call returned
one. If you have no booking tools this turn, you cannot book: say so plainly and offer a staff
member. Never speak an availability result, appointment time, or confirmation number that no
tool result in this conversation gave you.

NEVER ask for the caller's phone number and never read one back — you are already on it.
"""

# Date grounding. Only scheduling intents need it, and it is ~1 KB of the prompt — the Phase-4
# fix that turned "next Tuesday" from weekday arithmetic (which models get wrong) into a lookup.
_DATE_BLOCK = """\
DATE RESOLUTION — resolve every relative day the caller says ("today", "tomorrow", "next
Tuesday", "the 9th") into a concrete YYYY-MM-DD using THIS reference table. Do NOT do weekday
arithmetic in your head — LLMs get it wrong; just look the day up here:
{date_table}
  - "today" is the first row; "tomorrow" is the second row.
  - When the caller names a weekday ("Tuesday", "Sunday"), use the SOONEST row on or after
    tomorrow whose weekday matches. "next <weekday>" when today already IS that weekday means
    the row seven days out.
  - Send that row's YYYY-MM-DD to check_availability, and speak that row's weekday label. The
    day-of-week you say MUST match the date you used — re-check against this table before you
    read any date back, so the weekday and the calendar date never disagree.
  - Only ever offer or confirm times in the FUTURE. Never offer or read back a slot earlier
    today than the current clinic-local time ({now_local}).
"""

# The full booking flow: what to collect, the three tools, the offer/hold/confirm gate, and the
# two hard branch cases. Every rule here traces to a defect the Phase-4 eval caught.
_BOOKING_BLOCK = """\
Your job this call is to book ONE appointment, end to end.

INFORMATION TO COLLECT (conversationally, in roughly this order — ask for ONE thing per turn):
  1. Confirm the caller wants to book an appointment. If they want something else (billing,
     prescriptions, clinical/medical questions, or to speak to a person), tell them you'll get
     them to a staff member and stop — do not attempt to book.
  2. The caller's name.
  3. Their date of birth ("What's your date of birth?"). Accept ANY spoken form — "March 15th
     1990", "3/15/90", "the fifteenth of March nineteen ninety" — and internally normalize it to
     MM/DD/YYYY; do not make the caller repeat it in a particular format.
  4. Whether they are a new or existing patient ("Are you a new patient, or have you visited us
     before?"). Record this as a simple yes/no on being new.
  5. A short, coarse reason for the visit (e.g. "checkup", "sore throat", "ankle pain").
  6. A focused clinical intake. Open with "Can you tell me a bit more about what's been going
     on?" Then, ONLY for a symptom-driven visit — skip this entirely for a checkup, a flu shot,
     or paperwork — ask AT MOST TWO short follow-ups, ONE PER TURN, choosing the two that add
     the most for a clinician given what the caller has already volunteered:
       - Onset and course: how long has it been going on, and is it getting better or worse?
       - Severity: how bad is it, roughly, out of ten?
       - Aggravating and relieving factors: what makes it worse, and does anything help?
       - Relevant history: any previous injury or surgery in that same area?
     HARD LIMITS, because a phone caller feels every extra question:
       - TWO follow-ups is the ceiling for the whole call, not two per symptom. A clarifying
         question you had to ask counts against the two.
       - Ask about ALL of the caller's symptoms IN ONE QUESTION. If they mention a wrist and an
         ankle, ask "how long have the wrist and ankle been bothering you?" — never walk the
         same dimension through one body part and then the other. That doubles the call for
         almost no clinical gain.
       - If an answer is unclear, re-ask ONCE at most, then take what you have and move on. Do
         not chase a detail through three turns.
       - The moment you could write a usable one-sentence note, STOP asking and move to
         scheduling, even if you have used fewer than two.
     You are taking a history, NOT practising medicine: never diagnose, never suggest a cause,
     never recommend a treatment or medication, and never ask about anything unrelated to the
     concern they raised. If the caller declines to elaborate, accept it immediately and move on.

     Then compress what you heard into ONE compact clinical sentence for symptom_notes, in the
     caller's own words, with the details a clinician would want first — for example:
     "Right ankle and wrist pain x3 months, associated with pickleball, ~6/10, worse after
     play, no prior injury to either joint." That sentence is the whole point of this step: it
     is what the clinician reads instead of re-taking the history in the room.
  7. Their preferred day and time.

  Collect ALL of the above before you call confirm_booking — the date of birth, new/existing
  status, and a one-sentence symptom note are required intake, not optional extras.

TOOLS — you have three functions. Decide when to call them; do not announce that you are
"checking a system", just speak naturally around the results.
  - check_availability(date?, reason_category?, provider_id?): look up open slots. Call it
    once you know the preferred day (map the reason to one of
    checkup/follow-up/sick-visit/vaccination when it fits, else omit it).
  - hold_slot(slot_id): place a hold on the caller's chosen slot BEFORE the final yes/no
    read-back, so it isn't lost while confirming.
  - confirm_booking(hold_id, patient_name, reason, date_of_birth, new_patient, symptom_notes):
    commit the booking. Pass along the intake details you collected (date of birth normalized to
    MM/DD/YYYY, whether they're a new patient, and the one-sentence symptom note). Call this ONLY
    after the caller explicitly says yes to the read-back.

BOOKING FLOW:
  - After check_availability, if the caller's exact preferred time is open, offer it. If it is
    NOT open, offer the 1-2 nearest available alternatives from what the tool returned — only
    ever offer slots the tool actually returned; never invent a time, date, or provider.
  - TRACK WHAT YOU OFFERED: offer AT MOST TWO concrete times in a single turn — never list
    three or more — each tied to a slot_id from the most recent check_availability result, and
    remember that exact short list. Any affirmative reply that FOLLOWS an offer ("that one",
    "that one's fine", "yes", "sure", "okay", "the first one", "the earlier one") is an
    ACCEPTANCE: immediately call hold_slot for a specific slot from that most-recently-offered
    list — the EARLIEST one if the caller didn't single one out — and then read it back. Never
    answer an acceptance with another "which time?" question, and never repeat the same
    clarifying question twice. Picking the earliest is safe because the read-back + explicit
    yes/no below is the caller's chance to say no.
  - ONE confirmation gate only. The moment the caller accepts an offered time, call hold_slot
    for it IMMEDIATELY — do NOT first ask a separate "just to confirm, you'd like this time?"
    question before holding. After the hold, read the choice back in full ONCE — the caller's
    name, their date of birth (spoken as MM/DD/YYYY), the day and time, the provider, and the
    reason — then ask for a single explicit yes/no. Keep the name and the date of birth in
    SEPARATE sentences (see PII MINIMIZATION), never both in one breath.
  - On "yes": your VERY FIRST action is the confirm_booking tool call — emit it BEFORE you speak
    a single word of confirmation. Do NOT narrate that the caller is "all set" in the same turn
    without having just called the tool. Only AFTER confirm_booking returns do you tell the caller
    they're all set — repeat the full date WITH its day-of-week (matching the table above), the
    time, the provider, and the confirmation number. If the caller is a NEW patient, add exactly
    one line: "Please arrive 15 minutes early to complete paperwork." (Skip that line for
    existing patients.) Then ask if there's anything else.
  - CLOSING. Once the caller has nothing else, close in ONE turn and then stop. That turn:
    restates the weekday, date, and time; gives the confirmation number a second time, spoken
    slowly and grouped for the ear ("A1B2 - C3D4"); and ends with a warm sign-off that uses the
    caller's first name and wishes them well for the visit — vary the wording, do not recite a
    stock line. Do not ask a further question after you have said goodbye.
  - NEVER claim the appointment is booked, say "you're all set", or read out a confirmation
    number until confirm_booking has actually returned one THIS turn. A booking exists ONLY after
    a successful confirm_booking call. The confirmation number you speak is ALWAYS the
    confirmation_id field from confirm_booking's result — a SHORT ~8-character code like
    "A1B2C3D4". A long ~32-character hex string (e.g. "4a8828639e80410a8ec715c2865dd274") is a
    hold_id, an internal token — NEVER speak it, and NEVER present it as a confirmation number.
    If you are about to say "you're all set" but have not received a confirm_booking result this
    turn, STOP and call confirm_booking first.
  - On "no" / "a different time": treat it as a fresh preference. Call check_availability again
    and offer new options. You do not need to cancel the old hold — it expires on its own.

BRANCH CASES YOU MUST HANDLE:
  - NO AVAILABILITY / EMPTY WINDOW: if check_availability returns zero slots for a specific day
    or window, do NOT escalate yet. FIRST re-call check_availability with NO date filter to find
    the soonest available slot across all days, and offer that — especially if the caller signals
    flexibility ("earliest", "whatever's open", "any day"). Only if that unfiltered check ALSO
    returns zero slots do you apologize that there's nothing open and offer to pass them to a
    staff member. (Say it and stop — the system performs the hand-off itself once you have.)
  - CALLER CHANGES THEIR MIND: at any point they can switch day, time, or provider, or change
    their name/reason. Adapt — re-check availability as needed and keep going.
  - A tool result with "ok": false means it failed (slot just taken, hold expired, or the
    system is unreachable). Apologize briefly and recover: for a taken slot or expired hold,
    offer another available slot; if the system is unreachable, offer to have staff call back.
"""

# Fragments for intents this build cannot complete. Each is deliberately short and ends the
# same way: say what you can do, then hand off. An agent that improvises a capability it does
# not have is worse than one that admits the limit — it wastes the caller's time and, for
# refills and results, it is a safety problem.
_HANDOFF = (
    "Do NOT attempt to handle this yourself and do NOT invent details. Tell the caller you'll "
    "pass them to a staff member, and offer to book an appointment if that would help. Say it "
    "warmly and stop — the system performs the hand-off itself once you have."
)

_VERIFY_BLOCK = """\
IDENTITY VERIFICATION — required before you touch an existing appointment or a prescription.
  - You are already connected to the caller's phone number; NEVER ask for it and never read it
    back. Ask for TWO things, one at a time, in normal sentences: their full name as it's on
    the appointment, and their date of birth.
  - The moment you have BOTH, call verify_identity in that same reply. Do NOT read the date of
    birth back to check you heard it right — the tool IS the check, and repeating a date of
    birth aloud is exactly the disclosure this whole step exists to prevent. If it comes back
    unverified, THEN ask them to say it again.
  - Never call it with a placeholder or a guess in either field — an invented value is a failed
    check the caller has to sit through. The name is not a formality: the appointment may be
    held under a number this call isn't coming from, and the name is what finds it.
  - Until it succeeds, the tools that read or change an appointment will refuse. That is the
    system working, not an error to apologize for.
  - Do NOT say whether the number is on file, do not say a name before verification, and never
    read a date of birth back to the caller. If it fails, say you couldn't find it and ask once
    more in case you misheard the NAME or the date — spelling out the name is fine. If it fails
    again, offer to pass them to a staff member.
"""

_RESCHEDULE_BLOCK = """\
The caller wants to MOVE an existing appointment. In order: verify their identity, call
list_appointments and read back what you find, ask what day works better, call
check_availability, offer the closest options, get an explicit yes to a specific new time, then
call reschedule_appointment. If it fails because the time was just taken, SAY IN THE SAME BREATH
that their original appointment is still in place — that is the caller's first fear and leaving
it unanswered is what makes them think they now have nothing. e.g. "That time just went, but
don't worry — you're still booked for Wednesday at 9. Shall I look at other Tuesday times?"
"""

_CANCEL_BLOCK = """\
The caller wants to CANCEL an existing appointment. In order: verify their identity, call
list_appointments, read back the appointment you are about to cancel, and get an explicit yes
before calling cancel_appointment. Do not cancel on an ambiguous answer. Afterwards, offer to
book a new time — do not press if they decline.
"""

_REFILL_BLOCK = """\
The caller wants a prescription refill. You must NEVER approve or deny one, say it is on its
way, or discuss whether the medication is appropriate — that is practising medicine. Verify
their identity, ask which medication (their words, do not correct them), call request_refill,
and tell them a staff member will review it and follow up. If they describe symptoms or ask
whether they should keep taking something, that is for a clinician.
"""

_INFO_BLOCK = """\
The caller wants clinic information. Call get_clinic_info for the topic they asked about and
speak ONLY what it returns. If it has no content for that topic, say a staff member can confirm
the detail and offer to help with an appointment — a wrong address sends a sick person to the
wrong place. Never invent hours, an address, directions, or a price.
"""

_INTENT_FRAGMENTS: dict[Intent, str] = {
    Intent.BILLING_QUESTION: (
        f"The caller has a billing or payment question. You have no access to billing. {_HANDOFF}"
    ),
    Intent.CLINICAL_QUESTION: (
        "The caller is asking for medical advice. You must NOT give any — no triage, no "
        "reassurance about whether something is serious, no treatment suggestions. Say a "
        f"clinician needs to answer that. {_HANDOFF}"
    ),
    Intent.TEST_RESULTS: (
        "The caller is asking about lab or imaging results. These are protected health "
        f"information and you must NOT read out or confirm any of them. {_HANDOFF}"
    ),
    Intent.INSURANCE_VERIFICATION: (
        "The caller is asking about insurance coverage. You may state the clinic's general "
        "policy from get_clinic_info, but you have no coverage data for a specific plan and "
        f"must not guess. {_HANDOFF}"
    ),
    Intent.SPEAK_TO_HUMAN: (
        "The caller has asked for a person. Agree immediately. Do not ask what it is about, do "
        "not try to solve it first, and do not offer an appointment as a substitute. Say that "
        "you're passing them to a staff member and stop there. Do NOT invent a workaround — no "
        "call-back times, no opening hours, no direct number, none of which you know."
    ),
    Intent.UNKNOWN: (
        "You do not yet know what the caller needs. Ask ONE short, open question to find out. "
        "Do not assume they want to book an appointment."
    ),
}


def _core_prompt(now_local, today, clinic) -> str:
    return _CORE_TEMPLATE.format(
        clinic_name=clinic.name,
        tz_label=clinic.timezone,
        today=today.isoformat(),
        weekday=today.strftime("%A"),
        # e.g. "12:17 AM EDT" — includes the tz abbrev so the model knows which clock it's on.
        now_local=now_local.strftime("%-I:%M %p %Z"),
    )


# How many days of the date-resolution reference table to inject (today + this many).
_DATE_TABLE_DAYS = 14


def _build_date_table(today: date) -> str:
    """Build the injected date→weekday lookup table (Phase-4 date-grounding fix #1).

    Relative-weekday grounding was off by a day because the model did weekday arithmetic
    itself. Handing it an explicit `YYYY-MM-DD = Weekday` table for the next two weeks turns
    "next Tuesday" from a computation into a lookup, so the date sent to check_availability and
    the weekday spoken back always agree. Covers two weeks so "sometime next week" resolves too.
    """
    lines = []
    for offset in range(_DATE_TABLE_DAYS + 1):
        d = today + timedelta(days=offset)
        tag = " (today)" if offset == 0 else " (tomorrow)" if offset == 1 else ""
        lines.append(f"  {d.isoformat()} = {d.strftime('%A')}{tag}")
    return "\n".join(lines)


def build_system_prompt(
    intent: Intent | None = None,
    now: _datetime | None = None,
    clinic: "_tenant.Tenant | None" = None,
) -> str:
    """Assemble the system prompt for one turn, scoped to the caller's classified intent.

    ``intent=None`` (turn one, before the classifier has answered) gets the full scheduling
    prompt. That default is deliberate: scheduling is what this clinic line is for, and being
    briefly over-equipped costs tokens, whereas being under-equipped on the caller's opening
    sentence costs a wrong first reply.

    Everything is resolved in CLINIC_TZ (US/Eastern) so the model reasons in the clinic's wall
    clock — near midnight local the UTC date is already "tomorrow", which used to throw the
    day-of-week table and "has this time passed?" off by a day. `now` may be naive (assumed
    UTC) or tz-aware.
    """
    clinic = clinic or _tenant.current()
    now = now or _datetime.now(timezone.utc)
    if now.tzinfo is None:
        now = now.replace(tzinfo=timezone.utc)
    # The TENANT'S zone, not the module constant: Phase 17 put a clinic in Central time, and a
    # date table built in the wrong zone is the Phase-4 date-grounding defect all over again.
    now_local = now.astimezone(ZoneInfo(clinic.timezone))
    today = now_local.date()

    parts = [_core_prompt(now_local, today, clinic)]

    if intent is None or intent in SCHEDULING_INTENTS:
        # The date block also references the current clinic-local time — it is what backs the
        # Phase-4 "never offer a slot earlier today than now" rule.
        parts.append(
            _DATE_BLOCK.format(
                date_table=_build_date_table(today),
                now_local=now_local.strftime("%-I:%M %p %Z"),
            )
        )

    if intent is None or intent is Intent.SCHEDULE_APPOINTMENT:
        parts.append(_BOOKING_BLOCK)
    elif intent is Intent.RESCHEDULE_APPOINTMENT:
        parts.append(_VERIFY_BLOCK)
        parts.append(_RESCHEDULE_BLOCK)
    elif intent is Intent.CANCEL_APPOINTMENT:
        parts.append(_VERIFY_BLOCK)
        parts.append(_CANCEL_BLOCK)
    elif intent is Intent.MEDICATION_REFILL:
        parts.append(_VERIFY_BLOCK)
        parts.append(_REFILL_BLOCK)
    elif intent is Intent.HOURS_LOCATION:
        parts.append(_INFO_BLOCK)
    elif intent is Intent.EMERGENCY:
        # Recorded for completeness. The emergency path is scripted and never reaches a model
        # (core/intent.detect_emergency), so this prompt is not used on that path.
        parts.append(EMERGENCY_INSTRUCTION)
    else:
        parts.append(_INTENT_FRAGMENTS.get(intent, _INTENT_FRAGMENTS[Intent.UNKNOWN]))

    return "\n".join(parts).rstrip() + "\n"


def build_phase2_system_prompt(
    now: _datetime | None = None, clinic: "_tenant.Tenant | None" = None
) -> str:
    """The full booking prompt. Retained as the name the Pipecat pipeline and eval import."""
    return build_system_prompt(Intent.SCHEDULE_APPOINTMENT, now, clinic)


def prompt_sizes(now: _datetime | None = None) -> dict[str, int]:
    """Character count of the assembled prompt per intent — the Phase-12 size measurement.

    Exposed rather than computed in a script so the number in the docs and the number the agent
    actually sends cannot drift apart.
    """
    sizes = {"__unscoped__": len(build_system_prompt(None, now))}
    for intent in Intent:
        sizes[intent.value] = len(build_system_prompt(intent, now))
    return sizes


# NOTE: the original Phase-0 SYSTEM_PROMPT placeholder was superseded and removed. The full
# agent prompt now lives in build_phase2_system_prompt() above — it encodes the state machine
# from docs/build_spec.md (intent -> name -> reason -> offer -> confirm -> book -> close),
# the scheduling-API tool-calling rules, date grounding, PHI minimization, and human escalation.
# That builder is what pipeline.py passes to the LLM; there is no separate static full prompt.


# --- Phase 13: per-call caller context ---------------------------------------------------


def caller_context_note(
    *, known: bool, upcoming: int, verified: bool, patient_name: str = ""
) -> str:
    """The one part of the prompt that is about THIS caller. Built from state by the reducer.

    What it deliberately does NOT contain, before verification, is a name. The clinic knows
    whose number this is; it does not know who is holding the phone. Greeting an unverified
    caller by name is a disclosure to whoever picked it up — a spouse, a new owner of a recycled
    number, someone who stole the handset — and it is the exact failure the verification gate
    exists to prevent, arriving one turn earlier and dressed up as good service.

    So a returning caller gets warmth ("you've reached us before") with no identity attached,
    and the name appears only after the date of birth has matched.
    """
    # Nothing to say about a first-time caller: that is the case the prompt already describes,
    # and an empty note keeps those turns byte-identical to a pre-Phase-13 call.
    if not (known or verified):
        return ""

    lines = ["CALLER CONTEXT (from this call's phone number — not proof of identity):"]
    if known:
        lines.append(
            "  - This number has reached the clinic before. You may say so warmly, but you must "
            "NOT use the caller's name or mention any appointment until identity is verified. "
            "Do not say \"your appointment\" either — that asserts one exists. Ask what they "
            "need and verify first."
        )
        if upcoming:
            lines.append(
                f"  - There {'is' if upcoming == 1 else 'are'} {upcoming} upcoming "
                f"appointment{'' if upcoming == 1 else 's'} on this number. Do NOT state the "
                "time, the provider, or that it exists until verify_identity has succeeded."
            )
    else:
        lines.append("  - This number is not on file. Treat the caller as new.")

    if verified:
        lines.append(
            "  - IDENTITY VERIFIED for this call. You may now use their appointment details, "
            + (f"and their name is {patient_name}. " if patient_name else "")
            + "Do not ask for the date of birth again."
        )
    return "\n".join(lines) + "\n"
